//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeNSodeCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnimeSavePath")]
        public string AnimeSavePathConfigurationKey {
            get {
                return ((string)(this["AnimeSavePathConfigurationKey"]));
            }
            set {
                this["AnimeSavePathConfigurationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnimeSaveMode")]
        public string AnimeSaveModeConfigurationKey {
            get {
                return ((string)(this["AnimeSaveModeConfigurationKey"]));
            }
            set {
                this["AnimeSaveModeConfigurationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnimeSummaryMaxLength")]
        public string AnimeSummaryMaxLengthConfigurationKey {
            get {
                return ((string)(this["AnimeSummaryMaxLengthConfigurationKey"]));
            }
            set {
                this["AnimeSummaryMaxLengthConfigurationKey"] = value;
            }
        }
    }
}
